# This workflow will build wglinfo on Windows
name: Build (MinGW64)

on: [push]

jobs:
  build-windows-mingw:
    name: Build on Windows with GCC
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p

    - name: Configure wglinfo
      run: |
        mkdir "build"
        cmake -G Ninja -D BUILD_TREAT_WARNINGS_AS_ERRORS=ON -S . -B "./build"

    - name: Build wglinfo
      run: |
        cmake --build "./build" --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wglinfo-mingw
        path: build/wglinfo.exe
