# This workflow will build wglinfo on Windows
name: Build (MSVC)

on: [push]

jobs:
  build-windows-msvc:
    name: Build on Windows with MSVC
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x64

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Configure wglinfo
      run: |
        mkdir "build"
        cmake -T host=x64 -D BUILD_TREAT_WARNINGS_AS_ERRORS=ON -S . -B "./build"

    - name: Build wglinfo
      run: |
        cmake --build "./build" --config Release -- /m

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wglinfo-msvc
        path: build/Release
